# Generated by Django 2.2 on 2019-04-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('methodIdentifier', models.CharField(max_length=200)),
                ('methodType', models.CharField(max_length=200)),
                ('my_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.MyClass')),
            ],
        ),
        migrations.CreateModel(
            name='MyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputType', models.CharField(max_length=200)),
                ('my_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.MyMethod')),
            ],
        ),
        migrations.CreateModel(
            name='MyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('myIdentifier', models.CharField(max_length=200)),
                ('fieldType', models.CharField(max_length=200)),
                ('my_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.MyClass')),
            ],
        ),
    ]
