# Generated by Django 2.2 on 2019-04-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_myproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='my_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='converter.MyProject'),
            preserve_default=False,
        ),
    ]
