# Generated by Django 2.2 on 2019-04-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_myclass_my_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfield',
            name='my_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.MyClass'),
        ),
        migrations.AlterField(
            model_name='mymethod',
            name='my_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.MyClass'),
        ),
    ]
