# Generated by Django 2.2 on 2019-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20190429_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfield',
            name='defaultValue',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
