# Generated by Django 2.2 on 2019-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_myfield_defaultvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='parent_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
