# Generated by Django 2.2 on 2019-05-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_myclass_parent_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='parent_class',
            field=models.IntegerField(default=1),
        ),
    ]
