# Generated by Django 2.2 on 2019-05-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20190517_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='parent_class',
            field=models.IntegerField(default=-1),
        ),
    ]
