# Generated by Django 2.2 on 2019-05-17 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20190517_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='my_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.MyProject'),
        ),
    ]
